version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "master"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:35"
    assignees:
      - "AmorBielyi"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Go Dependency"
    rebase-strategy: "auto"

    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
